### ISSUE TITLE
Uploading a jfr resulted in versionNotSupportedException

### ISSUE THREAD

**Issue by sattishv** [kornilova203/FlameViewer#75]
Hi Team,

While uploading a jfr generated from Zulu Openjdk  in MacOS using chrome, we got the below listed exception
FlameViewer 1.0 
com.oracle.jmc.flightrecorder.internal.VersionNotSupportedException
	at com.oracle.jmc.flightrecorder.internal.FlightRecordingLoader.createChunkLoader(FlightRecordingLoader.java:223)
	at com.oracle.jmc.flightrecorder.internal.FlightRecordingLoader.readChunks(FlightRecordingLoader.java:168)
	at com.oracle.jmc.flightrecorder.internal.FlightRecordingLoader.loadStream(FlightRecordingLoader.java:51)
	at com.oracle.jmc.flightrecorder.JfrLoaderToolkit.loadFile(JfrLoaderToolkit.java:24)
	at com.oracle.jmc.flightrecorder.JfrLoaderToolkit.loadEvents(JfrLoaderToolkit.java:51)
	at com.oracle.jmc.flightrecorder.JfrLoaderToolkit.loadEvents(JfrLoaderToolkit.java:38)
	at com.github.kornilova_l.flight_parser.FlightParser.<init>(FlightParser.java:33)
	at com.github.kornilova203.flameviewer.converters.cflamegraph.JfrToStacksConverter.convert(JfrToStacksConverter.java:22)
	at com.github.kornilova203.flameviewer.converters.cflamegraph.JfrToCFlamegraphConverterFactoryCli$create$1.convert(JfrToCFlamegraphConverterFactoryCli.kt:14)
	at com.github.kornilova203.flameviewer.converters.cflamegraph.JfrToCFlamegraphConverterFactoryCli$create$1.convert(JfrToCFlamegraphConverterFactoryCli.kt:9)
	at com.github.kornilova203.flameviewer.converters.calltraces.ToCallTracesConverterFactoryCli$create$1.convert(ToCallTracesConverterFactoryCli.kt:25)
	at com.github.kornilova203.flameviewer.converters.calltraces.ToCallTracesConverterFactoryCli$create$1.convert(ToCallTracesConverterFactoryCli.kt:11)
	at com.github.kornilova203.flameviewer.converters.trees.ToTreesSetConverterFactory$create$2.convert(ToTreesSetConverterFactory.kt:19)
	at com.github.kornilova203.flameviewer.converters.trees.ToTreesSetConverterFactory$create$2.convert(ToTreesSetConverterFactory.kt:10)
	at com.github.kornilova203.flameviewer.server.TreeManager.updateTreesSet(TreeManager.kt:30)
	at com.github.kornilova203.flameviewer.server.TreeManager.getTree(TreeManager.kt:36)

**Comment by vrnvorona** [comment]
Same
